# Generated by Django 3.1.4 on 2021-01-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20210106_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.CharField(max_length=10, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Shelude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='День недели')),
                ('lecture', models.IntegerField(verbose_name='Номер пары')),
                ('Discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.discipline')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editor.group')),
            ],
        ),
    ]
