# Generated by Django 3.1.4 on 2021-01-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210112_2120'),
        ('editor', '0003_auto_20210112_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelude',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
