# Generated by Django 3.1.4 on 2021-01-13 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0004_auto_20210112_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discipline')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список дисциплин',
                'verbose_name_plural': 'Списки дисциплин',
                'unique_together': {('username', 'discipline')},
            },
        ),
    ]
