# Generated by Django 3.1.4 on 2021-01-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_disclist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelude',
        ),
    ]
