# Generated by Django 3.1.4 on 2021-01-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_delete_shelude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
