# Generated by Django 3.1.4 on 2021-01-14 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210113_1726'),
        ('editor', '0007_delete_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disclist',
            old_name='discipline',
            new_name='Discipline',
        ),
        migrations.AlterUniqueTogether(
            name='disclist',
            unique_together={('username', 'Discipline')},
        ),
    ]
