# Generated by Django 3.1.4 on 2021-01-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210113_1726'),
        ('editor', '0010_auto_20210114_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclist',
            name='Discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discipline'),
        ),
    ]
