# Generated by Django 3.1.4 on 2021-01-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20210114_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscList',
        ),
    ]
