# Generated by Django 3.1.4 on 2021-01-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disclist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disclist',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='disclist',
            name='username',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='DiscList',
        ),
    ]
