# Generated by Django 3.1.4 on 2021-01-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
        ('accounts', '0005_auto_20210112_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user',
            new_name='User',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editor.group'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='mid_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
