# Generated by Django 3.1.4 on 2021-01-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210112_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscList',
        ),
    ]
