# Generated by Django 3.1.4 on 2021-01-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_requestrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrole',
            name='Is_approved',
            field=models.BooleanField(null=True, verbose_name='Одобрено'),
        ),
    ]
