# Generated by Django 3.1.4 on 2021-01-14 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_requestrole_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestrole',
            unique_together={('User', 'Group')},
        ),
    ]
