# Generated by Django 3.1.4 on 2021-01-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_disclist'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, verbose_name='День')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Shelude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.day')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.group')),
                ('first_lect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_lect', to='main.discipline', verbose_name='Первая пара')),
                ('five_lect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='five_lect', to='main.discipline', verbose_name='Пятая пара')),
                ('four_lect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='four_lect', to='main.discipline', verbose_name='Четвертая пара')),
                ('second_lect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_lect', to='main.discipline', verbose_name='Вторая пара')),
                ('thrid_lect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thrid_lect', to='main.discipline', verbose_name='Третья пара')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'unique_together': {('Group', 'Day')},
            },
        ),
    ]
