# Generated by Django 3.1.4 on 2021-01-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210113_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
                ('is_done', models.BooleanField(null=True, verbose_name='Выполнен')),
                ('Lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecture')),
            ],
        ),
    ]
