# Generated by Django 3.1.4 on 2021-01-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lectrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectrequest',
            name='Lecture',
        ),
        migrations.AddField(
            model_name='lectrequest',
            name='Discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discipline'),
        ),
    ]
