# Generated by Django 3.1.4 on 2021-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_disclist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='image',
            field=models.ImageField(null=True, upload_to='bakot/static/bakot/imagination'),
        ),
    ]
