# Generated by Django 3.1.4 on 2021-04-04 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_lecture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(null=True, upload_to='update/'),
        ),
        migrations.CreateModel(
            name='deferred_lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название лекции')),
                ('text', models.TextField(verbose_name='Текст лекции')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(null=True, upload_to='update/')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.discipline')),
            ],
            options={
                'verbose_name': 'Отложенная лекция',
                'verbose_name_plural': 'Отложенные лекции',
            },
        ),
    ]
