# Generated by Django 3.1.4 on 2021-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210404_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deferred_lecture',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
