# Generated by Django 3.1.4 on 2021-04-04 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20210404_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deferred_lecture',
            new_name='DeferredLecture',
        ),
    ]
