# Generated by Django 3.1.4 on 2021-04-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_lecture_отложенная публикация'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='Отложенная публикация',
        ),
        migrations.AddField(
            model_name='lecture',
            name='rel_pub',
            field=models.BooleanField(default=None, verbose_name='Отложенная публикация'),
        ),
    ]
