# Generated by Django 3.1.4 on 2021-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210404_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
