# Generated by Django 3.1.4 on 2021-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210404_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='rel_pub',
            field=models.BooleanField(default=None, null=True, verbose_name='Отложенная публикация'),
        ),
    ]
