# Generated by Django 3.1.4 on 2021-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210404_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='rel_pub',
            field=models.BooleanField(default=False, null=True, verbose_name='Отложенная публикация'),
        ),
    ]
