# Generated by Django 3.1.4 on 2021-04-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210404_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='rel_pub',
        ),
    ]
