# Generated by Django 3.1.4 on 2021-04-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_lecture_rel_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='rel_pub',
            field=models.BooleanField(default=False, verbose_name='Отложенная публикация'),
        ),
    ]
