# Generated by Django 3.1.4 on 2021-04-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210404_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferredlecture',
            name='rel_pub',
            field=models.BooleanField(default=False, verbose_name='Отложенная публикация'),
        ),
        migrations.AlterField(
            model_name='deferredlecture',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='deferredlecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='update/'),
        ),
    ]
